xpos314/xpos314.web/Controllers/FriendController.cs
using Microsoft.AspNetCore.Mvc;
using xpos314.web.Models;
namespace xpos314.web.Controllers
{
    public class FriendController : Controller
    {
        private static List<Friend> friends = new List<Friend>()
     {
        new Friend() { Id = 1 , Name = "Anwar", Address = "Jakarta" },
        new Friend() { Id = 2 , Name = "Asti", Address = "Garut" }
     };

        public IActionResult Index()
        {

            ViewBag.listFriend = friends;

            return View(friends);
        }
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Friend friend)
        {
            friends.Add(friend);
            return RedirectToAction("Index");
        }
        //public IActionResult Edit(int id)
        //{
        //    Friend editFriend = friends.Find(i => i.Id == id)!;

        //    return View(editFriend);
        //}
        //[HttpPost]
        //public IActionResult Edit(Friend data)
        //{
        //    Friend friend1 = friends.Find(i => i.Id == data.Id)!;
        //    int index = friends.IndexOf(friend1);

        //    if (index > -1)
        //    {
        //        friends[index].Id = data.Id;
        //        friends[index].Name = data.Name;
        //        friends[index].Address = data.Address;
        //    }
        //    return RedirectToAction("Index");
        //}
        [HttpGet]
        [HttpPost]
        public IActionResult Edit(Friend data) 
        {
            Friend friend1 = friends.Find(i => i.Id == data.Id)!;
            int index = friends.IndexOf(data);
            if (HttpContext.Request.Method == "POST")
            {
                if (index > -1)
                {
                    friends[index].Id = data.Id;
                    friends[index].Name = data.Name;
                    friends[index].Address = data.Address;
                }
                return RedirectToAction("Index");
            }
            else
                return View(data);
        }
        public IActionResult Detail(int id)
        {
            Friend detailFriend = friends.Find(i => i.Id == id)!;

            return View(detailFriend);
        }
        //public IActionResult Delete(int id) 
        //{

        //    Friend deleteFriend = friends.Find(i => i.Id == id)!;

        //    return View(deleteFriend);
        //}
        //[HttpPost]
        //public IActionResult Delete(String id) 
        //{
        //    Friend deleteFriend = friends.Find(i => i.Id == int.Parse(id))!;
        //    friends.Remove(deleteFriend);
        //    return RedirectToAction("Index");
        //}
        [HttpGet]
        [HttpPost]
        public IActionResult Delete(int id) 
        {
            Friend data = friends.Find(i => i.Id == id)!;
            if (HttpContext.Request.Method == "POST")
            {
                friends.Remove(data);
                return RedirectToAction("Index");
            }
            else
                return View(data);
        }
    }
}

xpos314/xpos314.web/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using xpos314.viewmodels;
using xpos314.web.Services;

namespace xpos314.web.Controllers
{
	public class OrderController : Controller
	{
        private ProductService productService;
        private OrderService   orderService;
		private int idUser = 1;
		public OrderController(ProductService _productService, OrderService _orderService)
		{
			this.productService = _productService;
			this.orderService = _orderService;
		}
		public async Task<IActionResult> Catalog(VMSearchPage dataSearch) 
		{
			List<VMTblProduct> product = await productService.GetAllData();
			dataSearch.MinAmount = dataSearch.MinAmount == null ? decimal.MinValue : dataSearch.MinAmount;
			dataSearch.MaxAmount = dataSearch.MaxAmount == null ? decimal.MaxValue : dataSearch.MaxAmount;

			if(dataSearch.NameProduct != null)
				product = product.Where(a => a.NameProduct == dataSearch.NameProduct).ToList();

			if(dataSearch.MinAmount != null && dataSearch.MaxAmount != null)
				product = product.Where(a => a.Price >= dataSearch.MinAmount && a.Price <= dataSearch.MaxAmount).ToList();
			
			//Set Session in VMOrderHeader first load
			VMOrderHeader dataHeader = HttpContext.Session.GetComplexData<VMOrderHeader>("ListCart");
			if (dataHeader == null) 
			{
				dataHeader = new VMOrderHeader();
				dataHeader.ListDetails = new List<VMOrderDetail>();
			}

			var ListDetail = JsonConvert.SerializeObject(dataHeader.ListDetails);
			ViewBag.dataHeader = dataHeader;
			ViewBag.dataDetail = ListDetail;
			//End Session

			ViewBag.Search = dataSearch;
			ViewBag.CurrentPageSize = dataSearch.CurrentPageSize;

			return View(PaginatedList<VMTblProduct>.CreateAsync(product,dataSearch.pageNumber ?? 1 , dataSearch.pageSize ?? 3));
		}
		//Set Session in VMOrderHeader every add or minus
		[HttpPost]
		public JsonResult SetSession(VMOrderHeader dataHeader) 
		{
			HttpContext.Session.SetComplexData("ListCart", dataHeader);
			return Json("");
		}
		//End Session
		public JsonResult EndSession() 
		{
			HttpContext.Session.Remove("ListCart");
			return Json("");
		}
		public IActionResult OrderPreview(VMOrderHeader dataHeader) 
		{
			return PartialView(dataHeader);
		}
		public IActionResult SearchMenu() 
		{
			return PartialView();
		}

		[HttpPost]
		public async Task<JsonResult> SubmitOrder(VMOrderHeader dataHeader) 
		{
			dataHeader.IdCustomer = idUser;
		
			VMResponse response = await orderService.SubmitOrder(dataHeader);
			return Json(response);
		}
		public async Task<IActionResult> HistoryOrder(VMSearchPage dataSearch) 
		{
			int IdCustomer = idUser;
			List<VMOrderHeader> data = await orderService.ListHeaderDetails(IdCustomer);
			int count = await orderService.CountTransaction(IdCustomer);
			ViewBag.Count = count;
           
			dataSearch.MinAmount = dataSearch.MinAmount == null ? decimal.MinValue : dataSearch.MinAmount;
            dataSearch.MaxAmount = dataSearch.MaxAmount == null ? decimal.MaxValue : dataSearch.MaxAmount;
			
			dataSearch.MinDate = dataSearch.MinDate == null ? DateTime.MinValue : dataSearch.MinDate;
            dataSearch.MaxDate = dataSearch.MaxDate == null ? DateTime.MaxValue : dataSearch.MaxDate;

			if (!string.IsNullOrEmpty(dataSearch.CodeTransaction))
			{
				data = data.Where(a => a.CodeTransaction.ToLower()
				.Contains(dataSearch.CodeTransaction.ToLower())).ToList();
			}
			if (dataSearch.MinDate != null && dataSearch.MaxDate != null) 
			{
				data = data.Where(a => a.CreateDate >= dataSearch.MinDate && 
				a.CreateDate <= dataSearch.MaxDate).ToList();
			}
			if (dataSearch.MinAmount != null && dataSearch.MaxAmount != null) 
			{
				data = data.Where(a => a.Amount >= dataSearch.MinAmount && 
				a.Amount <= dataSearch.MaxAmount).ToList();
			}
			ViewBag.Search = dataSearch;

			return View(data);
        }
		public IActionResult Search() 
		{
			return PartialView();
		}
    }
}

xpos314/xpos314.web/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using System.Net;
using xpos314.datamodels;
using xpos314.viewmodels;
using xpos314.web.Services;

namespace xpos314.web.Controllers
{
    public class ProductController : Controller
    {
        private CategoryService categoryService;
        private VariantService variantService;
        private ProductService productService;
        private int idUser = 1;
        private readonly IWebHostEnvironment webHostEnvironment;
        public ProductController(ProductService _productService,VariantService _variantService, CategoryService _categoryService,IWebHostEnvironment _webhostEnvironment)
        {
            this.productService = _productService;
            this.categoryService = _categoryService;
            this.variantService = _variantService;
            this.webHostEnvironment = _webhostEnvironment;
        }
        public async Task<IActionResult> Index(string sortOrder, string searchString, string currentFilter, int? pageNumber, int? pageSize)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.CurrentPageSize = pageSize;
            ViewBag.NameSort = string.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.PriceSort = sortOrder == "price" ? "price_desc" : "price";
            if (searchString != null)
                pageNumber = 1;
            else
                searchString = currentFilter;

            ViewBag.CurrentFilter = searchString;

            List<VMTblProduct> datas = await productService.GetAllData();

            if (!string.IsNullOrEmpty(searchString))
            {
                datas = datas.Where(d => d.NameProduct.ToLower().Contains(searchString.ToLower())
                || d.NameVariant.ToLower().Contains(searchString.ToLower())
                || d.NameCategory.ToLower().Contains(searchString.ToLower())).ToList();
            }

            switch (sortOrder)
            {
                case "name_desc":
                    datas = datas.OrderByDescending(d => d.NameProduct).ToList();
                    break;
                case "price_desc":
                    datas = datas.OrderByDescending(d => d.Price).ToList();
                    break;
                case "price":
                    datas = datas.OrderBy(d => d.Price).ToList();
                    break;
                default:
                    datas = datas.OrderBy(d => d.NameProduct).ToList();
                    break;

            }
            return View(PaginatedList<VMTblProduct>.CreateAsync(datas, pageNumber ?? 1, pageSize ?? 3));
        }
        public async Task<JsonResult> GetDataByIdCategory(int id) 
        {
            List<VMTblVariant> data = await variantService.GetDataByIdCategory(id);
            return Json(data);
        }
        public string Upload(VMTblProduct dataParam) 
        {
            string uniqueFileName = "";

            if (dataParam.ImageFile != null) 
            {
                string uploadFolder = Path.Combine(webHostEnvironment.WebRootPath, "images");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + dataParam.ImageFile.FileName;
                string filePath = Path.Combine(uploadFolder, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create)) 
                {
                    dataParam.ImageFile.CopyTo(fileStream);
                }
            }

            return uniqueFileName;
        }
        public async Task<IActionResult> Create()
        {
            VMTblProduct data = new VMTblProduct();
            List<TblCategory> listCategory = await categoryService.GetAllData();
            List<VMTblVariant> listVariant = await variantService.GetAllData();
            ViewBag.ListCategory = listCategory;
            ViewBag.ListVariant = listVariant;
            return PartialView(data);
        }
        [HttpPost]
        public async Task<IActionResult> Create([FromForm]VMTblProduct dataParam)
        {
            if(dataParam.ImageFile != null)
                dataParam.Image = Upload(dataParam);

            VMResponse response = await productService.Create(dataParam);

            if (response.Success)
                return Json(new { dataRespon = response });

            return View(dataParam);
        }
        public async Task<IActionResult> Edit(int id) 
        {
            VMTblProduct data = await productService.GetDataById(id);

            List<TblCategory> listCategory = await categoryService.GetAllData();
            List<VMTblVariant> listVariant = await variantService.GetAllData();
            ViewBag.ListCategory = listCategory;
            ViewBag.ListVariant = listVariant;

            return PartialView(data);
        }
        [HttpPut]
        public async Task<IActionResult> Edit([FromForm]VMTblProduct dataParam) 
        {
            if (dataParam.ImageFile != null)
                dataParam.Image = Upload(dataParam);

            VMResponse response = await productService.Edit(dataParam);

            if (response.Success)
                return Json(new { dataRespon = response });

            return View(dataParam);
        }
        public async Task<IActionResult> Detail(int id)
        {
            VMTblProduct data = await productService.GetDataById(id);
            return PartialView(data);
        }
        public async Task<IActionResult> Delete(int id)
        {
            VMTblProduct data = await productService.GetDataById(id);
            return PartialView(data);
        }
        [HttpPost]
        public async Task<IActionResult> Deleted(int id)
        {
            VMResponse response = await productService.Delete(id);
            if (response.Success)
                return RedirectToAction("Index");

            return RedirectToAction("Index", id);
        }
    }
}

xpos314/xpos314.web/Controllers/RoleController.cs
using Microsoft.AspNetCore.Mvc;
using xpos314.datamodels;
using xpos314.viewmodels;
using xpos314.web.Services;

namespace xpos314.web.Controllers
{
    public class RoleController : Controller
    {
        private RoleService roleService;
        private int idUser = 1;
        public RoleController(RoleService _roleService)
        {
            this.roleService = _roleService;
        }
        public async Task<IActionResult> Index(string sortOrder, string searchString, string currentFilter, int? pageNumber, int? pageSize)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.CurrentPageSize = pageSize;
            ViewBag.NameSort = string.IsNullOrEmpty(sortOrder) ? "name_desc" : "";

            if (searchString != null)
                pageNumber = 1;
            else
                searchString = currentFilter;

            ViewBag.CurrentFilter = searchString;

            List<TblRole> datas = await roleService.GetAllData();

            if (!string.IsNullOrEmpty(searchString))
                datas = datas.Where(d => d.RoleName!.ToLower().Contains(searchString.ToLower())).ToList();
            switch (sortOrder)
            {
                case "name_desc":
                    datas = datas.OrderByDescending(d => d.RoleName).ToList();
                    break;

                default:
                    datas = datas.OrderBy(d => d.RoleName).ToList();
                    break;

            }
            return View(PaginatedList<TblRole>.CreateAsync(datas, pageNumber ?? 1, pageSize ?? 3));
        }
        public IActionResult Create()
        {
            TblRole data = new TblRole();
            return PartialView(data);
        }
        [HttpPost]
        public async Task<IActionResult> Create(TblRole dataParam)
        {
            dataParam.CreateBy = idUser;
            VMResponse response = await roleService.Create(dataParam);
            if (response.Success) 
            {
                return Json(new { dataRespon = response });
            }
            return View(dataParam);
        }
        public async Task<IActionResult> Edit(int id)
        {
            TblRole data = await roleService.GetDataById(id);
            return PartialView(data);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(TblRole dataParam)
        {
            dataParam.UpdateBy = idUser;
            VMResponse response = await roleService.Edit(dataParam);
            if (response.Success)
                return Json(new { dataRespon = response });
            return View(dataParam);
        }
        public async Task<IActionResult> Delete(int id)
        {
            TblRole data = await roleService.GetDataById(id);
            return PartialView(data);
        }
        [HttpPost]
        public async Task<IActionResult> Deleted(int id)
        {
            VMResponse response = await roleService.Delete(id);
            if (response.Success)
                return RedirectToAction("Index");

            return RedirectToAction("Index", id);
        }
        public async Task<IActionResult> Restore(int id) 
        {
            TblRole data = await roleService.GetDataById(id);
            return PartialView(data);
        }

        [HttpPost]
        public async Task<IActionResult> Restored(int id) 
        {
            VMResponse response = await roleService.Restore(id);
            if (response.Success)
                return RedirectToAction("Index");
            return RedirectToAction("Index", id);
        }
        public async Task<IActionResult> Detail(int id)
        {
            TblRole data = await roleService.GetDataById(id);
            return PartialView(data);
        }
        public async Task<JsonResult> CheckNameIsExist(string roleName)
        {
            bool isExist = await roleService.CheckRoleByName(roleName);
            return Json(isExist);
        }
    }
}

xpos314/xpos314.web/Views/Shared/_LayoutOld.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - xpos314.web</title>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/xpos314.web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">xpos314.web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Friend" asp-action="Index">Friend</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CategoryTry" asp-action="Index">Trial Category</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - xpos314.web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <!-- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body" id="body_modal">
                    ...
                </div>
            </div>
        </div>
    </div>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

xpos314/xpos314.web/Views/Shared/_Sidebar.cshtml
@using xpos314.web.Services
@inject AuthService authService
@{
    int IdCustomer = Context.Session.GetInt32("IdCustomer") ?? 0;
    int IdRole = Context.Session.GetInt32("IdRole") ?? 0;
    string NameCustomer = Context.Session.GetString("NameCustomer") ?? "";
    var menus = await authService.MenuAccess(IdRole);
}
<!-- ============================================================== -->
        <!-- Left Sidebar - style you can find in sidebar.scss  -->
        <!-- ============================================================== -->
        <aside class="left-sidebar" data-sidebarbg="skin6">
    <!-- Sidebar Menu -->
    <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
            <!-- Add icons to the links using the .nav-icon class
                 with font-awesome or any other icon font library -->
            @foreach (var parent in menus)
            {
                <li class="nav-item menu-open">
                    <a href="#" class="nav-link">
                        <i class="nav-icon @parent.MenuIcon"></i>
                        <p>
                            @parent.MenuName
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">

                        @foreach (var child in parent.ListChild)
                        {
                            <li class="nav-item">
                                <a asp-controller="@child.MenuController" asp-action="@child.MenuAction" class="nav-link">
                                    <i class="@child.MenuIcon nav-icon"></i>
                                    <p>@child.MenuName</p>
                                </a>
                            </li>
                        }
                    </ul>
                </li>
            }

        </ul>
    </nav>
    <!-- /.sidebar-menu -->
            <!-- Sidebar scroll-->
            <div class="scroll-sidebar" data-sidebarbg="skin6">
                <!-- Sidebar navigation-->
        @if (IdCustomer != 0) 
        {
            <nav class="sidebar-nav">
                <ul id="sidebarnav">
                    <li class="sidebar-item">
                        <a class="sidebar-link sidebar-link" asp-action="Index" asp-controller="Home"
                       aria-expanded="false">
                            <i data-feather="home" class="feather-icon"></i><span class="hide-menu">Dashboard</span>
                        </a>
                    </li>
                    <li class="list-divider"></li>
                    <li class="nav-small-cap"><span class="hide-menu">Master</span></li>

                    <li class="sidebar-item">
                        <a class="sidebar-link" asp-action="Index" asp-controller="Friend"
                       aria-expanded="false">
                            <i data-feather="tag" class="feather-icon"></i><span class="hide-menu">
                                Friend
                            </span>
                        </a>
                    </li>
                    <li class="sidebar-item">
                        <a class="sidebar-link sidebar-link" asp-action="Index" asp-controller="CategoryTry"
                       aria-expanded="false">
                            <i data-feather="message-square" class="feather-icon"></i><span class="hide-menu">(Trial)Category</span>
                        </a>
                    </li>
                    <li class="sidebar-item">
                        <a class="sidebar-link sidebar-link" asp-action="Index" asp-controller="VariantTry"
                       aria-expanded="false">
                            <i data-feather="calendar" class="feather-icon"></i><span class="hide-menu">(Trial)Variants</span>
                        </a>
                    </li>
                    <li class="sidebar-item">
                        <a class="sidebar-link sidebar-link" asp-action="Index" asp-controller="Category"
                       aria-expanded="false">
                            <i data-feather="message-square" class="feather-icon"></i><span class="hide-menu">Category</span>
                        </a>
                    </li>
                    <li class="sidebar-item">
                        <a class="sidebar-link sidebar-link" asp-action="Index" asp-controller="Variant"
                       aria-expanded="false">
                            <i data-feather="message-square" class="feather-icon"></i><span class="hide-menu">Variant</span>
                        </a>
                    </li>
                    <li class="sidebar-item">
                        <a class="sidebar-link sidebar-link" asp-action="Index" asp-controller="Product"
                       aria-expanded="false">
                            <i data-feather="message-square" class="feather-icon"></i><span class="hide-menu">Product</span>
                        </a>
                    </li>
                    <li class="list-divider"></li>
                    <li class="nav-small-cap"><span class="hide-menu">Transaction</span></li>

                    <li class="sidebar-item">
                        <a class="sidebar-link" asp-action="Catalog" asp-controller="Order" aria-expanded="false">
                            <i data-feather="tag" class="feather-icon"></i><span class="hide-menu"> Catalog </span>
                        </a>
                    </li>
                    <li class="sidebar-item">
                        <a class="sidebar-link sidebar-link" asp-action="HistoryOrder" asp-controller="Order" aria-expanded="false">
                            <i data-feather="message-square" class="feather-icon"></i><span class="hide-menu">Order History</span>
                        </a>
                    </li>
                    <li class="list-divider"></li>
                    <li class="nav-small-cap"><span class="hide-menu">User Configuration</span></li>
                    <li class="sidebar-item">
                        <a class="sidebar-link sidebar-link" asp-action="Index" asp-controller="Customer"
                       aria-expanded="false">
                            <i data-feather="tag" class="feather-icon"></i><span class="hide-menu">Customer</span>
                        </a>
                    </li>
                    <li class="sidebar-item">
                        <a class="sidebar-link sidebar-link" asp-action="Index" asp-controller="Role"
                       aria-expanded="false">
                            <i data-feather="message-square" class="feather-icon"></i><span class="hide-menu">Role</span>
                        </a>
                    </li>
                    <li class="list-divider"></li>
                    <li class="nav-small-cap"><span class="hide-menu">Kalbe</span></li>

                    <li class="sidebar-item">
                        <a class="sidebar-link" asp-action="Index" asp-controller="CustomerKalbe"
                       aria-expanded="false">
                            <i data-feather="tag" class="feather-icon"></i><span class="hide-menu">
                                Customer
                            </span>
                        </a>
                    </li>
                    <li class="sidebar-item">
                        <a class="sidebar-link sidebar-link" asp-action="Index" asp-controller="ProductKalbe"
                       aria-expanded="false">
                            <i data-feather="message-square" class="feather-icon"></i><span class="hide-menu">Produk</span>
                        </a>
                    </li>
                    <li class="sidebar-item">
                        <a class="sidebar-link sidebar-link" asp-action="Index" asp-controller="PenjualanKalbe"
                       aria-expanded="false">
                            <i data-feather="calendar" class="feather-icon"></i><span class="hide-menu">Penjualan</span>
                        </a>
                </ul>
            </nav>
        }
                <!-- End Sidebar navigation -->
            </div>
            <!-- End Sidebar scroll-->
        </aside>
        <!-- ============================================================== -->
        <!-- End Left Sidebar - style you can find in sidebar.scss  -->
        <!-- ============================================================== -->