xpos314/xpos314.web/Controllers/CategoryTryController.cs
using Microsoft.AspNetCore.Mvc;
using xpos314.datamodels;
using xpos314.viewmodels;
using xpos314.web.Services;

namespace xpos314.web.Controllers
{
    public class CategoryTryController : Controller
    {
        private readonly CategoryTryService categoryTryService;
        private readonly XPOS_314Context db;

        public CategoryTryController(XPOS_314Context _db)
        {
            this.db = _db;
            this.categoryTryService = new CategoryTryService(db);
        }
        public IActionResult Index()
        {
            List<VMTblCategory> dataView = categoryTryService.GetAllData();
            return View(dataView);
        }
        public IActionResult Create() 
        {
            VMTblCategory dataView = new VMTblCategory();
            return View(dataView);
        }

        [HttpPost]
        public IActionResult Create(VMTblCategory dataView) 
        {
            VMResponse response = new VMResponse();
            if (ModelState.IsValid) 
            {
                response = categoryTryService.Create(dataView);

                if (response.Success) 
                { 
                    return RedirectToAction("Index");
                }
            }
            response.Entity = dataView;
            return View(response.Entity);
        }
        public IActionResult Edit(int id) 
        {
            VMTblCategory dataView = categoryTryService.GetId(id);
            return View(dataView);
        }
        [HttpPost]
        public IActionResult Edit(VMTblCategory dataview) 
        {
            VMResponse response = new VMResponse();
            if (ModelState.IsValid)
            {
                response = categoryTryService.Edit(dataview);

                if (response.Success) 
                {
                    return RedirectToAction("Index");
                }
            }
            response.Entity = dataview;
            return View(response.Entity);
        }
        public IActionResult Detail(int id) 
        {
            VMTblCategory dataView = categoryTryService.GetId(id);
            
            return View(dataView);
        }
        public IActionResult Delete(int id) 
        {
            VMTblCategory dataView = categoryTryService.GetId(id);
            return View(dataView);
        }
        [HttpPost]
        public IActionResult Delete(VMTblCategory dataView) 
        {
            VMResponse response = categoryTryService.Delete(dataView);
            if (response.Success) 
            {
                return RedirectToAction("Index");
            }

            return View(response.Entity);
        }
    }
}

xpos314/xpos314.web/Views/CategoryTry/Create.cshtml
@using xpos314.viewmodels
@model VMTblCategory
@{
    Layout = null;
}
<div class="card">
    <div class="card-body">

<div class "h4 mb-4"> New Category </div>
<div></div>
<form asp-action="Create" method="post">
    <div class="mb-4 row">
        <label for="NameCategory" class="col-sm-2 col-form-label">Name</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" id="NameCategory" name="NameCategory" value="@Model.NameCategory">
            <span asp-validation-for="NameCategory" class="text-danger"></span>
        </div>
    </div>
    <div class="mb-4 row">
        <label for="Address" class="col-sm-2 col-form-label">Description</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" id="Description" name="Description">
        </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-10">
            <button type="submit" class="btn btn-primary">Submit</button>
            <a class="btn btn-light" asp-action="Index" asp-controller="CategoryTry"> Back to List</a>
        </div>
</form>
    </div>
    </div>

xpos314/xpos314.web/Views/CategoryTry/Delete.cshtml
@using xpos314.viewmodels
@model VMTblCategory
@{
    Layout = null;
}
<div class="card">
    <div class="card-body">
        <form asp-action="Delete" method="post">
            <input type="hidden" name="Id" value="@Model.Id" />
            <h3> Are you sure want to delete @Model.NameCategory ? </h3>
            <div class="modal-footer">
                <button type="submit" class="btn-primary">Sure!</button>
                <a asp-action="Index" class="btn-light">Back To List</a>
            </div>
        </form>
</div>
</div>

xpos314/xpos314.web/Views/CategoryTry/Detail.cshtml
@using xpos314.viewmodels
@model VMTblCategory
@{
    Layout = null;
}
<div class="card">
    <div class="card-body">

        <div class "h4 mb-4"> Detail of: @Model.NameCategory </div>
        <div></div>
            <div class="mb-4 row">
                <label for="NameCategory" class="col-sm-2 col-form-label">Name</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="NameCategory" name="NameCategory" value="@Model.NameCategory" readonly>
                    <span asp-validation-for="NameCategory" class="text-danger"></span>
                </div>
            </div>
            <div class="mb-4 row">
                <label for="Description" class="col-sm-2 col-form-label">Description</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="Description" name="Description" value="@Model.Description" readonly>
                </div>
            </div>
     
    </div>
</div>

xpos314/xpos314.web/Views/CategoryTry/Edit.cshtml
@using xpos314.viewmodels
@model VMTblCategory
@{
    Layout = null;  
}
<div class="card">
    <div class="card-body">

        <div class "h4 mb-4"> New Category </div>
        <div></div>
        <form asp-action="Edit" method="post">
            <input type="hidden" id="Ïd" name="Id" value="@Model.Id" />
            <div class="mb-4 row">
                <label for="NameCategory" class="col-sm-2 col-form-label">Name</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="NameCategory" name="NameCategory" value="@Model.NameCategory">
                    <span asp-validation-for="NameCategory" class="text-danger"></span>
                </div>
            </div>
            <div class="mb-4 row">
                <label for="Description" class="col-sm-2 col-form-label">Description</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="Description" name="Description" value="@Model.Description">
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-10">
                    <button type="submit" class="btn btn-primary">Submit</button>
                    <a class="btn btn-light" asp-action="Index" asp-controller="CategoryTry"> Back to List</a>
                </div>
        </form>
    </div>
</div>

xpos314/xpos314.web/Views/CategoryTry/Index.cshtml
@using xpos314.viewmodels
@{
    ViewData["Title"] = "Category Try";
}
<div class="card">
    <div class="card-body">

        <h1 class="card-title">@ViewData["Title"] </h1>
        <button class="btn btn-primary" id="btn_create"> Add Category </button>
        @*<div class="row">
            <form asp-action="Index" method="get" id="form_search">
            <div class="col-12">
                <div class="customize-input float-right">
                    <div class="input-group">
                        <input type="text" class="form-control" name="searchString" value="@ViewBag.currentFilter" placeholder="Search..." />
                        <div class="input-gruop-prepend">
                            <div class="input-group-text" id="btn_search">
                                <button type="button" class="btn btn-secondary" id="btn_search">Search</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
         </form>
      </div>*@
<table class="table table-hover">
    <thead>
        <tr>
            <th scope="col">Id</th>
            <th scope="col">NameCategory</th>
            <th scope="col">Description</th>
            <th scope="col">Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (VMTblCategory f in Model)
        {
            <tr>
                <th scope="row">@f.Id</th>
                <td>@f.NameCategory</td>
                <td>@f.Description</td>
                <td>
                            <a class="btn btn-primary btn_edit" data-id="@f.Id" style="cursor:pointer; color: white">Edit</a>
                            <a class="btn btn-success btn_detail" data-id="@f.Id" style="cursor:pointer; color: white">Detail</a>
                            <a class="btn btn-danger  btn_delete" data-id="@f.Id" style="cursor:pointer; color: white"> Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>
    </div>
</div>
<script>
    $(document).ready(function(){
        $("#btn_create").click(function(){
            $("#body_modal").empty()
            $("#body_modal").load("/CategoryTry/Create")
            $("#myModal").modal("show")
            //alert("Masuk")
        })
        $(".btn_edit").click(function(){
            var id = $(this).data("id")
            $("#body_modal").empty()
            $("#body_modal").load("/CategoryTry/Edit?id=" + id)
            $("#myModal").modal("show")
        })
        $(".btn_detail").click(function () {
            var id = $(this).data("id")
            $("#body_modal").empty()
            $("#body_modal").load("/CategoryTry/Detail?id=" + id)
            $("#myModal").modal("show")
        })
        $(".btn_delete").click(function () {
            var id = $(this).data("id")
            $("#body_modal").empty()
            $("#body_modal").load("/CategoryTry/Delete?id=" + id)
            $("#myModal").modal("show")
        })
        
    })
</script>