xpos314/xpos314.web/Controllers/VariantController.cs
using Microsoft.AspNetCore.Mvc;
using xpos314.datamodels;
using xpos314.viewmodels;
using xpos314.web.Services;

namespace xpos314.web.Controllers
{
	public class VariantController : Controller
	{
        private CategoryService categoryService;
        private VariantService variantService;
        private int idUser = 1;

        public VariantController(VariantService _variantService, CategoryService _categoryService)
        {
            this.categoryService = _categoryService;
            this.variantService = _variantService;
        }
        public async Task<IActionResult> Index(string sortOrder, string searchString, string currentFilter, int? pageNumber, int? pageSize)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.CurrentPageSize = pageSize;
            ViewBag.NameSort = string.IsNullOrEmpty(sortOrder) ? "name_desc" : "";

            if (searchString != null)
                pageNumber = 1;
            else
                searchString = currentFilter;

            ViewBag.CurrentFilter = searchString;

            List<VMTblVariant> datas = await variantService.GetAllData();

            if (!string.IsNullOrEmpty(searchString))
            {
                datas = datas.Where(d => d.NameVariant.ToLower().Contains(searchString.ToLower()) 
                ||d.Description.ToLower().Contains(searchString.ToLower()) 
                ||d.NameCategory.ToLower().Contains(searchString.ToLower())).ToList();
            }

            switch (sortOrder)
            {
                case "name_desc":
                    datas = datas.OrderByDescending(d => d.NameVariant).ToList();
                    break;

                default:
                    datas = datas.OrderBy(d => d.NameVariant).ToList();
                    break;

            }
            return View(PaginatedList<VMTblVariant>.CreateAsync(datas, pageNumber ?? 1, pageSize ?? 3));
        }
        public async Task<IActionResult> Create() 
        {
            VMTblVariant data = new VMTblVariant();
            List<TblCategory> listCategory = await categoryService.GetAllData();
            ViewBag.ListCategory = listCategory;
            return PartialView(data);
        }
        [HttpPost]
        public async Task<IActionResult> Create(VMTblVariant dataParam) 
        {
            VMResponse response = await variantService.Create(dataParam);

            if (response.Success)
                return Json(new { dataRespon = response });

            return View(dataParam);
        }
        public async Task<IActionResult> Edit(int id) 
        {
            VMTblVariant data = await variantService.GetDataById(id);
            List<TblCategory> listCategory = await categoryService.GetAllData();
            ViewBag.ListCategory = listCategory;
            return PartialView(data);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(VMTblVariant dataParam)
        {
            VMResponse response = await variantService.Edit(dataParam);
            dataParam.UpdateBy = idUser;
            if (response.Success)
                return Json(new { dataRespon = response });
            return View(dataParam);
        }
        public async Task<IActionResult> Delete(int id)
        {
            VMTblVariant data = await variantService.GetDataById(id);
            return PartialView(data);
        }
        [HttpPost]
        public async Task<IActionResult> Deleted(int id)
        {
            VMResponse response = await variantService.Delete(id);
            if (response.Success)
                return RedirectToAction("Index");

            return RedirectToAction("Index", id);
        }
        public async Task<IActionResult> Detail(int id)
        {
            VMTblVariant data = await variantService.GetDataById(id);
            return PartialView(data);
        }
        public async Task<IActionResult> Restore(int id) 
        {
            VMTblVariant data = await variantService.GetDataById(id);
            return PartialView(data);
        }
        [HttpPost]
        public async Task<IActionResult> Restored(int id)
        {
            VMResponse response = await variantService.Restore(id);
            if (response.Success)
                return RedirectToAction("Index");
            return RedirectToAction("Index",id);
        }
    }
}

xpos314/xpos314.web/Views/Variant/Create.cshtml
@using xpos314.viewmodels
@model VMTblVariant
@{
	Layout = null;
	ViewData["Title"] = "Create Variant";
}
<div class="card mt-4">
	<div class="card-body">
		<h4>@ViewData["Title"]</h4>
		<form asp-action="Create" method="post" id="form_input">
			<div class="form-group row mb-2">
				<label for="NameVariant" class="col-sm-4 col-form-label">Name Variant</label>
				<div class="col-sm-8">
					<input required type="text" class="form-control" name="NameVariant" id="NameVariant" value="@Model.NameVariant">
				</div>
			</div>
			<div class="mb-4 row">
                <label for="IdCategory" class="col-sm-4 col-form-label">Name Category</label>
                <div class="col-sm-8">
                    @Html.DropDownList("IdCategory",new SelectList(ViewBag.ListCategory, "Id", "NameCategory"),"--Choose Category--",new {@class = "form-control"})
                </div>
            </div>

			<div class="form-group row mb-2">
				<label for="Description" class="col-sm-4 col-form-label">Description</label>
				<div class="col-sm-8">
					<input type="text" class="form-control" name="Description" id="Description" value="@Model.Description">
				</div>
			</div>
			<div class="form-group row">
				<div class="col-sm-10">
					<button type="submit" class="btn btn-primary">Submit</button>
					<a class="btn btn-secondary" asp-controller="Variant" asp-action="Index">Back</a>
				</div>
			</div>
		</form>
	</div>
</div>

<script>
	$("#form_input").validate({
		errorClass: "text-danger",
		rules: {
			NameVariant: {
				required: true,
				minlength: 5
			},
			IdCategory: {
				required: true
			}
		},
		messages: {
			NameVariant: {
				required: "Please fill Name of the Variant",
				minlength: "The name must consist of at least 5 characters"
			},
			IdCategory: {
				required: "Please choose the Name Category"
			}
		},
		submitHandler: function (form) {
			var dataForm = $(form).serialize()
			$.ajax({
				url: "/Variant/Create",
				data: dataForm,
				method: "post",
				dataType: "json",
				success: function (respon) {
					var data = respon.dataRespon
					if (data.success) {
						$("#myModal").modal("hide")
						toastr.success(
							data.message,
							'',
							{
								timeOut: 500,
								fadeOut: 500,
								onHidden: function () {
									window.location.reload()
								}
							}
						)
					} else {
						toastr.error(data.message)
					}
				}
			})
		}
	});
</script>

xpos314/xpos314.web/Views/Variant/Delete.cshtml
@using xpos314.viewmodels
@model VMTblVariant

<div class="card">
    <div class="card-body">
        <form asp-action="Deleted" method="post">
            <input type="hidden" id="Id" name="Id" value="@Model.Id"/>

            <h3>Are you sure for delete @Model.NameVariant ?</h3>

            <div class="modal-footer">
                <button type="submit" class="btn btn-primary">Yes</button>
                <a asp-action="Index" class="btn btn-secondary">Back to List</a>
            </div>
        </form>
    </div>
</div>

xpos314/xpos314.web/Views/Variant/Detail.cshtml
@using xpos314.viewmodels
@model VMTblVariant
@{
	Layout = null;
	ViewData["Title"] = "Edit Variant";
}
<div class="card mt-4">
	<div class="card-body">
		<h4>@ViewData["Title"]</h4>
			<div class="form-group row mb-2">
				<div class="form-group row mb-2">
					<label for="NameVariant" class="col-sm-4 col-form-label">Name Variant</label>
					<div class="col-sm-8">
						<input type="text" class="form-control" name="NameVariant" id="NameVariant" value="@Model.NameVariant" readonly>
					</div>
				</div>

				<div class="mb-4 row">
					<label for="IdCategory" class="col-sm-4 col-form-label">Name Category</label>
					<div class="col-sm-8">
					<input type="text" class="form-control" name="NameCategory" id="NameCategory" value="@Model.NameCategory" readonly>
				</div>
				</div>

				<div class="form-group row mb-2">
					<label for="Description" class="col-sm-4 col-form-label">Description</label>
					<div class="col-sm-8">
						<input type="text" class="form-control" name="Description" id="Description" value="@Model.Description" readonly>
					</div>
				</div>
				<div class="form-group row">
					<div class="col-sm-10">
						<a class="btn btn-secondary" asp-controller="Variant" asp-action="Index">Back</a>
					</div>
				</div>
	</div>
</div>

xpos314/xpos314.web/Views/Variant/Edit.cshtml
@using xpos314.viewmodels
@model VMTblVariant
@{
	Layout = null;
	ViewData["Title"] = "Edit Variant";
}
<div class="card mt-4">
	<div class="card-body">
		<h4>@ViewData["Title"]</h4>
		<form asp-action="Edit" method="post" id="form_input">
				<div class="form-group row mb-2">
				<div class="col-sm-8">
					<input required type="hidden" class="form-control" name="Id" id="Id" value="@Model.Id">
				</div>
			<div class="form-group row mb-2">
				<label for="NameVariant" class="col-sm-4 col-form-label">Name Variant</label>
				<div class="col-sm-8">
					<input required type="text" class="form-control" name="NameVariant" id="NameVariant" value="@Model.NameVariant">
				</div>
			</div>
			<div class="mb-4 row">
				<label for="IdCategory" class="col-sm-4 col-form-label">Name Category</label>
				<div class="col-sm-8">
					@Html.DropDownList("IdCategory",new SelectList(ViewBag.ListCategory, "Id", "NameCategory"),"--Choose Category--",new {@class = "form-control"})
				</div>
			</div>

			<div class="form-group row mb-2">
				<label for="Description" class="col-sm-4 col-form-label">Description</label>
				<div class="col-sm-8">
					<input type="text" class="form-control" name="Description" id="Description" value="@Model.Description">
				</div>
			</div>
			<div class="form-group row">
				<div class="col-sm-10">
					<button type="submit" class="btn btn-primary">Submit</button>
					<a class="btn btn-secondary" asp-controller="Variant" asp-action="Index">Back</a>
				</div>
			</div>
		</form>
	</div>
</div>

<script>
	$("#form_input").validate({
		errorClass: "text-danger",
		rules: {
			NameVariant: {
				required: true,
				minlength: 5
			},
			IdCategory: {
				required: true
			}
		},
		messages: {
			NameVariant: {
				required: "Please fill Name of the Variant",
				minlength: "The name must consist of at least 5 characters"
			},
			IdCategory: {
				required: "Please choose the Name Category"
			}
		},
		submitHandler: function (form) {
			var dataForm = $(form).serialize()
			$.ajax({
				url: "/Variant/Edit",
				data: dataForm,
				method: "post",
				dataType: "json",
				success: function (respon) {
					var data = respon.dataRespon
					if (data.success) {
						$("#myModal").modal("hide")
						toastr.success(
							data.message,
							'',
							{
								timeOut: 500,
								fadeOut: 500,
								onHidden: function () {
									window.location.reload()
								}
							}
						)
					} else {
						toastr.error(data.message)
					}
				}
			})
		}
	});
</script>

xpos314/xpos314.web/Views/Variant/Index.cshtml
@using xpos314.datamodels
@using xpos314.viewmodels
@using System.Globalization
@model PaginatedList<VMTblVariant>

<h3>Variant</h3>


<div class="card">
	<div class="card-header">
		@*        <button id="btn_create" class="btn btn-primary">Create</button>*@
		<form asp-action="Index" asp-route-pageSize="@ViewBag.CurrentPageSize">
			<div class="row mb-3">
				<div class="col-12">
					<div class="d-flex justify-content-between">
						<button type="button" class="btn btn-primary" id="btn_create" style="color:white; border-radius:5px;">
							Create
						</button>

						<div class="input-group w-50">
							<input type="text" class="form-control" id="searchString" name="searchString"
								   value="@ViewBag.currentFilter" placeholder="Search..." />
							<div class="input-group-prepend">
								<div class="input-group-text" style="cursor:pointer" id="btn_search"><i class="fas fa-search"></i></div>
							</div>
							<div class="input-group-prepend">
								<div class="input-group-text">
									<a asp-action="Index">
									<i class="fas fa-redo"></i>
									</a>
									</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</form>
		<!-- /.card-header -->
		<div class="card-body table-responsive p-0">
			<table class="table table-hover mb-3">
				<thead>
					<tr>
						<th>
							<a asp-action="Index" asp-route-sortOrder="@ViewBag.NameSort">
								<i class="fas fa-sort"></i>
								Name Variant
							</a>
						</th>
						<th>Name Category</th>
						<th>Description</th>
						<th>Available</th>
						<th>Create Date</th>
						<th>Action</th>
					</tr>
				</thead>
				<tbody>
					@if (Model.Count != 0)
					{
						@foreach (var item in Model)
						{
							string available = item.IsDelete == true ? "No" : "Yes";
							
							<tr>
								<td>@item.NameVariant</td>
								<td>@item.NameCategory</td>
								<td>@item.Description</td>
								<td>
									@if(@item.IsDelete == true )
									{
										@available
									}
									else
									{
										@available
										<i class="fas fa-check"></i>
									}
								</td>
								<td>@item.CreateDate.ToString("dddd, dd MMMM yyyy HH:mm:ss",new CultureInfo("id-ID"))</td>
								<td>
									@if (item.IsDelete == false) 
									{
										<a class="btn btn-primary btn_detail" dataid="@item.Id" style="color:white">Detail</a>
										<a class="btn btn-warning btn_edit" dataid="@item.Id"><i style="color:white;" data-feather="edit"></i></a>
										<a class="btn btn-danger  btn_delete" dataid="@item.Id" style="color:white"> Delete </a>
									}
									else
									{
										<a class="btn btn-success btn_restore" dataid="@item.Id" style="color:white">Restore</a>
									}
								</td>

							</tr>
						}
					}
					else
					{
						<tr>
							<td colspan="3">
								<i>Data not found</i>
							</td>
						</tr>
					}
				</tbody>
			</table>
		</div>
		<!-- /.card-body -->

		<div class="card-footer">
			@{
				var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
				var nextDisabled = !Model.HasNextPage ? "disabled" : "";
			}
			<div class="row">
				<div class="col-2">

					<form asp-action="Index" id="form_pagesize">
						@*submitnya menggunakan jquery*@
						<select name="PageSize" id="PageSize"
								class="form-control">
							<option value="3">3</option>
							<option value="5">5</option>
							<option value="10">10</option>
						</select>
					</form>
				</div>
				<div class="col-10">
					Page @Model.PageIndex of @Model.TotalPages
					<a asp-action="Index"
					   asp-route-sortOrder="@ViewBag.CurrentSort"
					   asp-route-pageNumber="@(Model.PageIndex + 1)"
					   asp-route-currentFilter="@ViewBag.CurrentFilter"
					   asp-route-pageSize="@ViewBag.CurrentPageSize"
					   class="btn btn-info float-right @nextDisabled">
						Next
					</a>
					<a asp-action="Index"
					   asp-route-sortOrder="@ViewBag.CurrentSort"
					   asp-route-pageNumber="@(Model.PageIndex - 1)"
					   asp-route-currentFilter="@ViewBag.CurrentFilter"
					   asp-route-pageSize="@ViewBag.CurrentPageSize"
					   class="btn btn-info float-right @prevDisabled">
						Previous
					</a>
				</div>
			</div>
		</div>
	</div>
</div>


<script>
	$(document).ready(function () {
		$("select_show").val(@ViewBag.currentShowData)

		$("#btn_toast").click(function () {
			toastr.success("Berhasil")
		});

		$("#btn_create").click(function () {
			$(".modal-body").empty();
			$(".modal-body").load("/Variant/Create")
			$("#myModal").modal("show");
		});

		$(".btn_detail").click(function () {

			var id = $(this).attr("dataid")
			$(".modal-body").empty();
			$(".modal-body").load("/Variant/Detail?id=" + id)
			$("#myModal").modal("show");
		});

		$(".btn_edit").click(function () {

			var id = $(this).attr("dataid")
			$(".modal-body").empty();
			$(".modal-body").load("/Variant/Edit?id=" + id)
			$("#myModal").modal("show");
		});

		$(".btn_delete").click(function () {
			var id = $(this).attr("dataid");
			$(".modal-body").empty();
			$(".modal-body").load("/Variant/Delete?id=" + id)
			$("#myModal").modal("show");
		});

		$(".btn_restore").click(function () {
			var id = $(this).attr("dataid");
			$(".modal-body").empty();
			$(".modal-body").load("/Variant/Restore?id=" + id)
			$("#myModal").modal("show");
		});
		$("#PageSize").val(@ViewBag.CurrentPageSize)

		$("#PageSize").change(function () {
			$("#form_pagesize").submit();
		})
	});
</script>

xpos314/xpos314.web/Views/Variant/Restore.cshtml
@using xpos314.viewmodels
@model VMTblVariant

<div class="card">
    <div class="card-body">
        <form asp-action="Restored" method="post">
            <input type="hidden" id="Id" name="Id" value="@Model.Id"/>
            
            <h3>Are you sure want to restore @Model.NameVariant ?</h3>

            <div class="modal-footer">
                <button type="submit" class="btn btn-primary">Yes</button>
                <a asp-action="Index" class="btn btn-secondary">Back to List</a>
            </div>
        </form>
    </div>
</div>